spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/gongmo?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 798513yy
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: GSF-HikariCP-POOL
      max-lifetime: 2000000
      connection-timeout: 30000
  jpa:
  hibernate:
    connection:
    provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      hibernate:
        #show_sql: true
        show_sql: false
        format_sql: true
        use_sql: true
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    allow-bean-definition-overriding: true
